apiVersion: v1
kind: Namespace 
metadata:
  name: cicd

---

apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: cicd
 name: cicd-test
 labels:
   app: cicd-test
spec:
 strategy:
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: cicd-test
 template:
   metadata:
     labels:
       app: cicd-test
   spec:
     containers:
     - name: cicd-test
       image: avicity/cicd-test:v1
       ports:
       - containerPort: 8080
